services:
  caddy:
    container_name: ${OSGS_NAMESPACE}-caddy
    image: caddy:${OSGS_CADDY_VERSION}
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./caddy:/etc/caddy:ro
    environment:
      OSGS_HOSTNAME: ${OSGS_HOSTNAME}
      OSGS_USERNAME: ${OSGS_USERNAME}
    command: >
      sh -c "export OSGS_ADHOC_HASHED_PASSWORD=$(caddy hash-password --plaintext ${OSGS_PASSWORD}) && 
             caddy run --config /etc/caddy/Caddyfile --adapter caddyfile"

  postgis:
    ports: !override
      - "${OSGS_POSTGIS_PORT}:5432"

  geoserver:
    ports: !reset []
    expose:
      - "8080"

  pgadmin:
    ports: !reset []
    expose:
      - "80"
      - "443"

  jupyterlab:
    ports: !reset []
    expose:
      - "8888"

  hub:
    ports: !reset []
    expose:
      - "5000"
    environment:
      - "CARD_1_HREF=Open,/jupyterlab/"
      - "CARD_2_HREF=Open,/pgadmin/"
      - "CARD_3_CONNECTIONINFO=Username,${OSGS_USERNAME};Password,${OSGS_PASSWORD};Database name,${OSGS_DB_NAME};Host,${OSGS_HOSTNAME};Port,5432"
      - "CARD_4_HREF=Open,/geoserver/web/"
      - "CARD_4_CONNECTIONINFO=Username,${OSGS_USERNAME};Password,${OSGS_PASSWORD};Host,${OSGS_HOSTNAME}/geoserver/"
