# Start dev setup (building images locally):
# docker compose -p sandbox_dev -f docker-compose.yml -f docker-compose-dev.yml up --build

services:
  jupyterlabgeoenv:
    build: ./jupyterlabgeoenv/
    image: !reset null
   
  content:
    build: ./content/
    image: !reset null

  hub:
    build: ./hub/
    image: !reset null
    